docker run --gpus all \
    --name sglang_node_tf5 \
    --network host \
    --shm-size 32g \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    -v $(pwd):/workspace \
    --env "HF_TOKEN=$HF_TOKEN" \
    --env "CUDA_VISIBLE_DEVICES=0" \
    --env "NCCL_SOCKET_IFNAME=enp1s0f1np1" \
    --env "NCCL_DEBUG=INFO" \
    --env "NCCL_IB_DISABLE=0" \
    --env "NCCL_IB_GID_INDEX=3" \
    --env "MASTER_ADDR=192.168.100.11" \
    --env "MASTER_PORT=50000" \
    --env "WORLD_SIZE=2" \
    --env "NCCL_IB_TIMEOUT=22" \
    --env "NCCL_IB_RETRY_CNT=7" \
    --env "NCCL_ASYNC_ERROR_HANDLING=1" \
    --env "NCCL_BLOCKING_WAIT=1" \
    --env "TORCH_DISTRIBUTED_TIMEOUT=1800" \
    --ipc=host \
    -it --rm \
    scitrera/dgx-spark-sglang:0.5.9-dev2-acab24a7-t5 \
    python3 -m sglang.launch_server \
        --model-path Qwen/Qwen3.5-35B-A3B \
        --served-model-name qwen3.5-35b \
        --tp-size 2 \
        --nnodes 2 \
        --node-rank 0 \
        --dist-init-addr 192.168.100.11:50000 \
        --host 0.0.0.0 \
        --port 30000 \
        --attention-backend triton \
        --trust-remote-code
